version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: line-ghl-fastapi-middleware
    restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
